kind: Deployment
apiVersion: apps/v1
metadata:
 name: nginx-deployment
 # Labels of deployment resource
 labels:
   app: nginx
   tier: frontend
   purpose: deployment
spec:
 replicas: {{ .Values.deployment.replicas }} #assume this will change
 selector:
   matchLabels:
     app: nginx
     tier: frontend
     purpose: deployment
 template:
   metadata:
     labels:
       app: nginx
       tier: frontend
       purpose: deployment
   spec:
     containers:
     - name: nginx
       image: nginx:{{ .Values.deployment.imageVersion }} # Version will be changing frequently
       ports:
       - containerPort: 80