kind: Service
apiVersion: v1
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector: #Lables are used as selectors
    app: nginx
    tier: frontend
    purpose: deployment
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80
      nodePort: 30007
